---
# tasks file for setup_db


- name: Copy db file into app dir
  copy:
          src: /home/ubuntu/HandsOn/db_to_use/notejam.db 
          dest: /home/ubuntu/HandsOn/django/notejam/notejam.db
          remote_src: yes


- name: Sync db with app
  command: ./manage.py syncdb
  args:
          chdir: /home/ubuntu/HandsOn/django/notejam/


- name: Migrate
  command: ./manage.py migrate
  args:
          chdir: /home/ubuntu/HandsOn/django/notejam/


- name: Copy systemd service file to system
  copy:
          src: /home/ubuntu/utility/runserver.service
          dest: /etc/systemd/system
          owner: root
          group: root
          remote_src: yes
  become: true
  notify:
    - Run server
